# Generated by Django 3.2.4 on 2021-07-07 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='proofesion_Periodista',
            new_name='profesion_Periodista',
        ),
    ]
