# Generated by Django 3.2.4 on 2021-07-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_proofesion_periodista_usuarios_profesion_periodista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.IntegerField(null=True, primary_key=True, serialize=False, verbose_name='Id Noticia')),
                ('titulo', models.CharField(max_length=200, null=True, verbose_name='titulo')),
                ('descripcion', models.CharField(max_length=500, null=True, verbose_name='descripcion')),
                ('fecha', models.DateField(null=True, verbose_name='fecha')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen')),
            ],
        ),
        migrations.AlterField(
            model_name='contacto',
            name='titulo',
            field=models.CharField(max_length=128, null=True, verbose_name='titulo'),
        ),
    ]
