# Generated by Django 3.2.4 on 2021-07-08 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210708_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuarios', verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='id_noticia',
            field=models.IntegerField(null=True, primary_key=True, serialize=False, verbose_name='id_noticia'),
        ),
    ]
